// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "development" | "staging" | "production";
	ENABLE_TEST_AUTH_MOCK: "false";
	NEXT_PUBLIC_APP_URL: "http://localhost:3000" | "https://staging.parikshaverse.in" | "https://parikshaverse.in";
	EMAIL_FROM: "ParikshaVerse Dev <auth@parikshaverse.in>" | "ParikshaVerse Staging <auth@staging.parikshaverse.in>" | "ParikshaVerse <auth@parikshaverse.in>";
	DB: D1Database;
}
