import type { QuestionWithOptions } from "./types";

const now = new Date("2026-09-25T12:00:00.000Z");

/**
 * Verified fixture question test bank for development, testing, and UI validation.
 *
 * PROVENANCE NOTICE:
 * All questions in this file are synthetic educational fixtures authored specifically
 * for engine verification and automated tests. None of these questions represent
 * copyrighted, scraped, or official previous year questions (PYQs).
 */
export const FIXTURE_QUESTIONS: QuestionWithOptions[] = [
  // --------------------------------------------------------------------------
  // PHYSICS: Kinematics -> Vectors and Scalars (5 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_phy_vec_01",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_kinematics",
    topicId: "exam_neet_physics_kinematics_vectors-and-scalars",
    text: "Two vectors A and B have equal magnitudes of 5 units. If the angle between them is 60°, what is the magnitude of their scalar (dot) product?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Scalar product is given by A · B = |A||B| cos θ = 5 × 5 × cos(60°) = 25 × 0.5 = 12.5 units.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pv01_a", questionId: "q_fix_phy_vec_01", displayOrder: 1, optionKey: "A", text: "12.5 units", isCorrect: true },
      { id: "opt_fix_pv01_b", questionId: "q_fix_phy_vec_01", displayOrder: 2, optionKey: "B", text: "25.0 units", isCorrect: false },
      { id: "opt_fix_pv01_c", questionId: "q_fix_phy_vec_01", displayOrder: 3, optionKey: "C", text: "21.65 units", isCorrect: false },
      { id: "opt_fix_pv01_d", questionId: "q_fix_phy_vec_01", displayOrder: 4, optionKey: "D", text: "0 units", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_vec_02",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_kinematics",
    topicId: "exam_neet_physics_kinematics_vectors-and-scalars",
    text: "If the vector product (cross product) of two non-zero vectors A and B is zero, what is the geometric relationship between them?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "The magnitude of the cross product is |A × B| = |A||B| sin θ. When sin θ = 0, θ is 0° or 180°, meaning the vectors are collinear (parallel or anti-parallel).",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pv02_a", questionId: "q_fix_phy_vec_02", displayOrder: 1, optionKey: "A", text: "They are perpendicular to each other", isCorrect: false },
      { id: "opt_fix_pv02_b", questionId: "q_fix_phy_vec_02", displayOrder: 2, optionKey: "B", text: "They are parallel or anti-parallel", isCorrect: true },
      { id: "opt_fix_pv02_c", questionId: "q_fix_phy_vec_02", displayOrder: 3, optionKey: "C", text: "They must have equal magnitudes", isCorrect: false },
      { id: "opt_fix_pv02_d", questionId: "q_fix_phy_vec_02", displayOrder: 4, optionKey: "D", text: "They form an angle of 45°", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_vec_03",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_kinematics",
    topicId: "exam_neet_physics_kinematics_vectors-and-scalars",
    text: "What is the unit vector in the direction of vector V = 3i + 4j?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Magnitude |V| = √(3² + 4²) = √25 = 5. The unit vector is V / |V| = (3i + 4j) / 5 = 0.6i + 0.8j.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pv03_a", questionId: "q_fix_phy_vec_03", displayOrder: 1, optionKey: "A", text: "0.6i + 0.8j", isCorrect: true },
      { id: "opt_fix_pv03_b", questionId: "q_fix_phy_vec_03", displayOrder: 2, optionKey: "B", text: "3i + 4j", isCorrect: false },
      { id: "opt_fix_pv03_c", questionId: "q_fix_phy_vec_03", displayOrder: 3, optionKey: "C", text: "0.5i + 0.5j", isCorrect: false },
      { id: "opt_fix_pv03_d", questionId: "q_fix_phy_vec_03", displayOrder: 4, optionKey: "D", text: "(3i + 4j) / 25", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_vec_04",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_kinematics",
    topicId: "exam_neet_physics_kinematics_vectors-and-scalars",
    text: "A boat moves across a river with velocity 8 m/s relative to water due North. The river flows East at 6 m/s. What is the resultant speed of the boat relative to the riverbank?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Because North and East are perpendicular, the resultant speed is √(8² + 6²) = √(64 + 36) = √100 = 10 m/s.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pv04_a", questionId: "q_fix_phy_vec_04", displayOrder: 1, optionKey: "A", text: "14 m/s", isCorrect: false },
      { id: "opt_fix_pv04_b", questionId: "q_fix_phy_vec_04", displayOrder: 2, optionKey: "B", text: "10 m/s", isCorrect: true },
      { id: "opt_fix_pv04_c", questionId: "q_fix_phy_vec_04", displayOrder: 3, optionKey: "C", text: "2 m/s", isCorrect: false },
      { id: "opt_fix_pv04_d", questionId: "q_fix_phy_vec_04", displayOrder: 4, optionKey: "D", text: "7 m/s", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_vec_05",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_kinematics",
    topicId: "exam_neet_physics_kinematics_vectors-and-scalars",
    text: "Under what condition is the magnitude of the sum of two vectors |A + B| equal to the magnitude of their difference |A - B|?",
    type: "single_choice",
    difficulty: "hard",
    explanation: "|A + B|² = A² + B² + 2A·B, and |A - B|² = A² + B² - 2A·B. Equating the two gives 4A·B = 0, which implies A · B = 0. Therefore, A and B are perpendicular.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pv05_a", questionId: "q_fix_phy_vec_05", displayOrder: 1, optionKey: "A", text: "When A and B are parallel", isCorrect: false },
      { id: "opt_fix_pv05_b", questionId: "q_fix_phy_vec_05", displayOrder: 2, optionKey: "B", text: "When A and B are perpendicular", isCorrect: true },
      { id: "opt_fix_pv05_c", questionId: "q_fix_phy_vec_05", displayOrder: 3, optionKey: "C", text: "When |A| = |B| only", isCorrect: false },
      { id: "opt_fix_pv05_d", questionId: "q_fix_phy_vec_05", displayOrder: 4, optionKey: "D", text: "When A and B are anti-parallel", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },

  // --------------------------------------------------------------------------
  // PHYSICS: Laws of Motion -> Newton's Laws and Inertia (4 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_phy_lom_01",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_laws-of-motion",
    topicId: "exam_neet_physics_laws-of-motion_newtons-laws-and-inertia",
    text: "A constant net force of 20 N acts on a mass of 4 kg initially at rest. What is the speed acquired by the mass after 3 seconds?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Acceleration a = F / m = 20 / 4 = 5 m/s². Velocity v = u + at = 0 + (5 × 3) = 15 m/s.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pl01_a", questionId: "q_fix_phy_lom_01", displayOrder: 1, optionKey: "A", text: "15 m/s", isCorrect: true },
      { id: "opt_fix_pl01_b", questionId: "q_fix_phy_lom_01", displayOrder: 2, optionKey: "B", text: "20 m/s", isCorrect: false },
      { id: "opt_fix_pl01_c", questionId: "q_fix_phy_lom_01", displayOrder: 3, optionKey: "C", text: "12 m/s", isCorrect: false },
      { id: "opt_fix_pl01_d", questionId: "q_fix_phy_lom_01", displayOrder: 4, optionKey: "D", text: "60 m/s", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_lom_02",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_laws-of-motion",
    topicId: "exam_neet_physics_laws-of-motion_newtons-laws-and-inertia",
    text: "Which physical quantity represents the rate of change of linear momentum according to Newton's Second Law?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Newton's Second Law states that the rate of change of linear momentum of an object is directly proportional to the applied net force: F = dp/dt.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pl02_a", questionId: "q_fix_phy_lom_02", displayOrder: 1, optionKey: "A", text: "Impulse", isCorrect: false },
      { id: "opt_fix_pl02_b", questionId: "q_fix_phy_lom_02", displayOrder: 2, optionKey: "B", text: "External Force", isCorrect: true },
      { id: "opt_fix_pl02_c", questionId: "q_fix_phy_lom_02", displayOrder: 3, optionKey: "C", text: "Kinetic Energy", isCorrect: false },
      { id: "opt_fix_pl02_d", questionId: "q_fix_phy_lom_02", displayOrder: 4, optionKey: "D", text: "Work done", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_lom_03",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_laws-of-motion",
    topicId: "exam_neet_physics_laws-of-motion_newtons-laws-and-inertia",
    text: "A 0.15 kg ball moving with a speed of 20 m/s is stopped by a player in 0.1 s. What is the average force exerted on the player's hands?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Initial momentum p_i = m × u = 0.15 × 20 = 3.0 kg·m/s. Final momentum p_f = 0. Average force F = Δp / Δt = 3.0 / 0.1 = 30 N.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pl03_a", questionId: "q_fix_phy_lom_03", displayOrder: 1, optionKey: "A", text: "30 N", isCorrect: true },
      { id: "opt_fix_pl03_b", questionId: "q_fix_phy_lom_03", displayOrder: 2, optionKey: "B", text: "3 N", isCorrect: false },
      { id: "opt_fix_pl03_d", questionId: "q_fix_phy_lom_03", displayOrder: 3, optionKey: "C", text: "15 N", isCorrect: false },
      { id: "opt_fix_pl03_c", questionId: "q_fix_phy_lom_03", displayOrder: 4, optionKey: "D", text: "300 N", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_phy_lom_04",
    examId: "exam_neet",
    subjectId: "exam_neet_physics",
    chapterId: "exam_neet_physics_laws-of-motion",
    topicId: "exam_neet_physics_laws-of-motion_newtons-laws-and-inertia",
    text: "When an elevator ascends with a uniform upward acceleration 'a', what is the apparent weight of a person of mass 'm' standing on a scale inside?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "By applying Newton's second law: N - mg = ma => N = m(g + a). Thus, the apparent weight increases.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_pl04_a", questionId: "q_fix_phy_lom_04", displayOrder: 1, optionKey: "A", text: "m(g - a)", isCorrect: false },
      { id: "opt_fix_pl04_b", questionId: "q_fix_phy_lom_04", displayOrder: 2, optionKey: "B", text: "m(g + a)", isCorrect: true },
      { id: "opt_fix_pl04_c", questionId: "q_fix_phy_lom_04", displayOrder: 3, optionKey: "C", text: "mg", isCorrect: false },
      { id: "opt_fix_pl04_d", questionId: "q_fix_phy_lom_04", displayOrder: 4, optionKey: "D", text: "m(a - g)", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },

  // --------------------------------------------------------------------------
  // CHEMISTRY: Chemical Bonding -> VSEPR and Hybridisation (4 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_chm_bnd_01",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-bonding",
    topicId: "exam_neet_chemistry_chemical-bonding_vsepr-and-hybridisation",
    text: "According to VSEPR theory, what is the geometry of a molecule with sp³ hybridization having 2 bonding pairs and 2 lone pairs (e.g. H₂O)?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "With 4 electron domains (2 bond pairs + 2 lone pairs), the electron geometry is tetrahedral, but the molecular geometry is bent / V-shaped due to lone pair repulsion.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_cb01_a", questionId: "q_fix_chm_bnd_01", displayOrder: 1, optionKey: "A", text: "Linear", isCorrect: false },
      { id: "opt_fix_cb01_b", questionId: "q_fix_chm_bnd_01", displayOrder: 2, optionKey: "B", text: "Bent / Angular", isCorrect: true },
      { id: "opt_fix_cb01_c", questionId: "q_fix_chm_bnd_01", displayOrder: 3, optionKey: "C", text: "Trigonal planar", isCorrect: false },
      { id: "opt_fix_cb01_d", questionId: "q_fix_chm_bnd_01", displayOrder: 4, optionKey: "D", text: "Tetrahedral", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_chm_bnd_02",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-bonding",
    topicId: "exam_neet_chemistry_chemical-bonding_vsepr-and-hybridisation",
    text: "What is the hybridization of the central sulfur atom in SF₆?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Sulfur has 6 valence electrons and forms 6 single bonds with fluorine without lone pairs. 6 steric domains corresponds to sp³d² hybridization (octahedral geometry).",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_cb02_a", questionId: "q_fix_chm_bnd_02", displayOrder: 1, optionKey: "A", text: "sp³d", isCorrect: false },
      { id: "opt_fix_cb02_b", questionId: "q_fix_chm_bnd_02", displayOrder: 2, optionKey: "B", text: "sp³d²", isCorrect: true },
      { id: "opt_fix_cb02_c", questionId: "q_fix_chm_bnd_02", displayOrder: 3, optionKey: "C", text: "sp³", isCorrect: false },
      { id: "opt_fix_cb02_d", questionId: "q_fix_chm_bnd_02", displayOrder: 4, optionKey: "D", text: "dsp²", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_chm_bnd_03",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-bonding",
    topicId: "exam_neet_chemistry_chemical-bonding_vsepr-and-hybridisation",
    text: "Which of the following molecules possesses a zero dipole moment despite having polar bonds?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "BF₃ has a symmetrical trigonal planar geometry (120° bond angles). The three equal B-F dipole vectors cancel each other out completely, yielding a net dipole moment of zero.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_cb03_a", questionId: "q_fix_chm_bnd_03", displayOrder: 1, optionKey: "A", text: "NH₃", isCorrect: false },
      { id: "opt_fix_cb03_b", questionId: "q_fix_chm_bnd_03", displayOrder: 2, optionKey: "B", text: "BF₃", isCorrect: true },
      { id: "opt_fix_cb03_c", questionId: "q_fix_chm_bnd_03", displayOrder: 3, optionKey: "C", text: "H₂O", isCorrect: false },
      { id: "opt_fix_cb03_d", questionId: "q_fix_chm_bnd_03", displayOrder: 4, optionKey: "D", text: "SO₂", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_chm_bnd_04",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-bonding",
    topicId: "exam_neet_chemistry_chemical-bonding_vsepr-and-hybridisation",
    text: "What is the correct order of repulsive interactions according to VSEPR theory?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Lone pairs occupy more spatial domain around the central nucleus than bonding pairs. Hence: Lone Pair - Lone Pair > Lone Pair - Bond Pair > Bond Pair - Bond Pair.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_cb04_a", questionId: "q_fix_chm_bnd_04", displayOrder: 1, optionKey: "A", text: "lp-lp > lp-bp > bp-bp", isCorrect: true },
      { id: "opt_fix_cb04_b", questionId: "q_fix_chm_bnd_04", displayOrder: 2, optionKey: "B", text: "bp-bp > lp-bp > lp-lp", isCorrect: false },
      { id: "opt_fix_cb04_c", questionId: "q_fix_chm_bnd_04", displayOrder: 3, optionKey: "C", text: "lp-bp > lp-lp > bp-bp", isCorrect: false },
      { id: "opt_fix_cb04_d", questionId: "q_fix_chm_bnd_04", displayOrder: 4, optionKey: "D", text: "lp-lp = lp-bp = bp-bp", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },

  // --------------------------------------------------------------------------
  // CHEMISTRY: Thermodynamics -> First Law and Enthalpy (3 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_chm_thm_01",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-thermodynamics",
    topicId: "exam_neet_chemistry_chemical-thermodynamics_first-law-and-enthalpy",
    text: "In an adiabatic expansion of an ideal gas, which of the following statements is always true?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "In an adiabatic process, no heat is exchanged with surroundings (q = 0). By the first law ΔU = q + w = w. As the gas expands (w < 0), internal energy decreases (ΔU < 0).",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_ct01_a", questionId: "q_fix_chm_thm_01", displayOrder: 1, optionKey: "A", text: "Heat exchange q = 0", isCorrect: true },
      { id: "opt_fix_ct01_b", questionId: "q_fix_chm_thm_01", displayOrder: 2, optionKey: "B", text: "Temperature remains constant (ΔT = 0)", isCorrect: false },
      { id: "opt_fix_ct01_c", questionId: "q_fix_chm_thm_01", displayOrder: 3, optionKey: "C", text: "Work done is zero", isCorrect: false },
      { id: "opt_fix_ct01_d", questionId: "q_fix_chm_thm_01", displayOrder: 4, optionKey: "D", text: "Change in internal energy is positive", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_chm_thm_02",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-thermodynamics",
    topicId: "exam_neet_chemistry_chemical-thermodynamics_first-law-and-enthalpy",
    text: "For the reaction N₂(g) + 3H₂(g) → 2NH₃(g), what is the relationship between ΔH and ΔU at temperature T?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Δn_g = moles of gaseous products - moles of gaseous reactants = 2 - (1 + 3) = -2. Using ΔH = ΔU + Δn_g RT, we get ΔH = ΔU - 2RT.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_ct02_a", questionId: "q_fix_chm_thm_02", displayOrder: 1, optionKey: "A", text: "ΔH = ΔU - 2RT", isCorrect: true },
      { id: "opt_fix_ct02_b", questionId: "q_fix_chm_thm_02", displayOrder: 2, optionKey: "B", text: "ΔH = ΔU + 2RT", isCorrect: false },
      { id: "opt_fix_ct02_c", questionId: "q_fix_chm_thm_02", displayOrder: 3, optionKey: "C", text: "ΔH = ΔU", isCorrect: false },
      { id: "opt_fix_ct02_d", questionId: "q_fix_chm_thm_02", displayOrder: 4, optionKey: "D", text: "ΔH = ΔU - RT", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_chm_thm_03",
    examId: "exam_neet",
    subjectId: "exam_neet_chemistry",
    chapterId: "exam_neet_chemistry_chemical-thermodynamics",
    topicId: "exam_neet_chemistry_chemical-thermodynamics_first-law-and-enthalpy",
    text: "Which of the following thermodynamic properties is an intensive property?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "An intensive property does not depend on the quantity of matter present. Density is intensive, while mass, volume, and enthalpy are extensive.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_ct03_a", questionId: "q_fix_chm_thm_03", displayOrder: 1, optionKey: "A", text: "Density", isCorrect: true },
      { id: "opt_fix_ct03_b", questionId: "q_fix_chm_thm_03", displayOrder: 2, optionKey: "B", text: "Volume", isCorrect: false },
      { id: "opt_fix_ct03_c", questionId: "q_fix_chm_thm_03", displayOrder: 3, optionKey: "C", text: "Enthalpy", isCorrect: false },
      { id: "opt_fix_ct03_d", questionId: "q_fix_chm_thm_03", displayOrder: 4, optionKey: "D", text: "Internal Energy", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },

  // --------------------------------------------------------------------------
  // BIOLOGY: Cell Structure -> Cell Theory and Organelles (4 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_bio_cel_01",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-theory-and-organelles",
    text: "Which cell organelle is known as the site of aerobic cellular respiration and ATP generation?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Mitochondria are double-membraned organelles where the Krebs cycle and oxidative phosphorylation take place, generating cellular ATP.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_bc01_a", questionId: "q_fix_bio_cel_01", displayOrder: 1, optionKey: "A", text: "Golgi apparatus", isCorrect: false },
      { id: "opt_fix_bc01_b", questionId: "q_fix_bio_cel_01", displayOrder: 2, optionKey: "B", text: "Mitochondria", isCorrect: true },
      { id: "opt_fix_bc01_c", questionId: "q_fix_bio_cel_01", displayOrder: 3, optionKey: "C", text: "Endoplasmic reticulum", isCorrect: false },
      { id: "opt_fix_bc01_d", questionId: "q_fix_bio_cel_01", displayOrder: 4, optionKey: "D", text: "Lysosome", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cel_02",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-theory-and-organelles",
    text: "Who proposed the concept 'Omnis cellula-e cellula' modifying Schleiden and Schwann's cell theory?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Rudolf Virchow (1855) first explained that cells divided and new cells are formed from pre-existing cells ('Omnis cellula-e cellula').",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_bc02_a", questionId: "q_fix_bio_cel_02", displayOrder: 1, optionKey: "A", text: "Robert Hooke", isCorrect: false },
      { id: "opt_fix_bc02_b", questionId: "q_fix_bio_cel_02", displayOrder: 2, optionKey: "B", text: "Rudolf Virchow", isCorrect: true },
      { id: "opt_fix_bc02_c", questionId: "q_fix_bio_cel_02", displayOrder: 3, optionKey: "C", text: "Antonie van Leeuwenhoek", isCorrect: false },
      { id: "opt_fix_bc02_d", questionId: "q_fix_bio_cel_02", displayOrder: 4, optionKey: "D", text: "Robert Brown", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cel_03",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-theory-and-organelles",
    text: "Which of the following organelles is NOT bounded by any membrane?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Ribosomes are non-membrane bound ribonucleoprotein complexes found in both prokaryotic and eukaryotic cells.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_bc03_a", questionId: "q_fix_bio_cel_03", displayOrder: 1, optionKey: "A", text: "Lysosome", isCorrect: false },
      { id: "opt_fix_bc03_b", questionId: "q_fix_bio_cel_03", displayOrder: 2, optionKey: "B", text: "Peroxisome", isCorrect: false },
      { id: "opt_fix_bc03_c", questionId: "q_fix_bio_cel_03", displayOrder: 3, optionKey: "C", text: "Ribosome", isCorrect: true },
      { id: "opt_fix_bc03_d", questionId: "q_fix_bio_cel_03", displayOrder: 4, optionKey: "D", text: "Vacuole", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cel_04",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-theory-and-organelles",
    text: "The fluid mosaic model of the plasma membrane was proposed by Singer and Nicolson in which year?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "S.J. Singer and G.L. Nicolson proposed the widely accepted fluid mosaic model of the cell membrane in 1972.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_bc04_a", questionId: "q_fix_bio_cel_04", displayOrder: 1, optionKey: "A", text: "1972", isCorrect: true },
      { id: "opt_fix_bc04_b", questionId: "q_fix_bio_cel_04", displayOrder: 2, optionKey: "B", text: "1953", isCorrect: false },
      { id: "opt_fix_bc04_c", questionId: "q_fix_bio_cel_04", displayOrder: 3, optionKey: "C", text: "1984", isCorrect: false },
      { id: "opt_fix_bc04_d", questionId: "q_fix_bio_cel_04", displayOrder: 4, optionKey: "D", text: "1935", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },

  // --------------------------------------------------------------------------
  // BIOLOGY: Cell Cycle -> Cell Cycle and Cell Division (4 questions)
  // --------------------------------------------------------------------------
  {
    id: "q_fix_bio_cyc_01",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-cycle-and-cell-division",
    text: "In which phase of the eukaryotic cell cycle does DNA replication occur?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "DNA replication and duplication of the centriole take place during the S (Synthesis) phase of interphase.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_by01_a", questionId: "q_fix_bio_cyc_01", displayOrder: 1, optionKey: "A", text: "G₁ phase", isCorrect: false },
      { id: "opt_fix_by01_b", questionId: "q_fix_bio_cyc_01", displayOrder: 2, optionKey: "B", text: "S phase", isCorrect: true },
      { id: "opt_fix_by01_c", questionId: "q_fix_bio_cyc_01", displayOrder: 3, optionKey: "C", text: "G₂ phase", isCorrect: false },
      { id: "opt_fix_by01_d", questionId: "q_fix_bio_cyc_01", displayOrder: 4, optionKey: "D", text: "M phase", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cyc_02",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-cycle-and-cell-division",
    text: "During which sub-stage of Prophase I does crossing over between non-sister chromatids of homologous chromosomes take place?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Recombination nodules appear and crossing over occurs during the Pachytene stage, mediated by the recombinase enzyme.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_by02_a", questionId: "q_fix_bio_cyc_02", displayOrder: 1, optionKey: "A", text: "Leptotene", isCorrect: false },
      { id: "opt_fix_by02_b", questionId: "q_fix_bio_cyc_02", displayOrder: 2, optionKey: "B", text: "Zygotene", isCorrect: false },
      { id: "opt_fix_by02_c", questionId: "q_fix_bio_cyc_02", displayOrder: 3, optionKey: "C", text: "Pachytene", isCorrect: true },
      { id: "opt_fix_by02_d", questionId: "q_fix_bio_cyc_02", displayOrder: 4, optionKey: "D", text: "Diakinesis", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cyc_03",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-cycle-and-cell-division",
    text: "What structure forms at the centromere of chromosomes to which spindle fibers attach during metaphase?",
    type: "single_choice",
    difficulty: "easy",
    explanation: "Kinetochores are disc-shaped protein complexes situated on the centromere that serve as attachment points for spindle microtubules.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_by03_a", questionId: "q_fix_bio_cyc_03", displayOrder: 1, optionKey: "A", text: "Kinetochore", isCorrect: true },
      { id: "opt_fix_by03_b", questionId: "q_fix_bio_cyc_03", displayOrder: 2, optionKey: "B", text: "Centrosome", isCorrect: false },
      { id: "opt_fix_by03_c", questionId: "q_fix_bio_cyc_03", displayOrder: 3, optionKey: "C", text: "Telomere", isCorrect: false },
      { id: "opt_fix_by03_d", questionId: "q_fix_bio_cyc_03", displayOrder: 4, optionKey: "D", text: "Chromocenter", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q_fix_bio_cyc_04",
    examId: "exam_neet",
    subjectId: "exam_neet_biology",
    chapterId: "exam_neet_biology_cell-structure-and-function",
    topicId: "exam_neet_biology_cell-structure-and-function_cell-cycle-and-cell-division",
    text: "Cells in the quiescent stage (G₀) of the cell cycle are characterized by which state?",
    type: "single_choice",
    difficulty: "medium",
    explanation: "Cells in the G₀ stage remain metabolically active but do not proliferate unless called on to do so depending on the requirement of the organism.",
    source: "ParikshaVerse Synthetic Testbank",
    provenance: "fixture",
    status: "active",
    options: [
      { id: "opt_fix_by04_a", questionId: "q_fix_bio_cyc_04", displayOrder: 1, optionKey: "A", text: "They are dead and decaying", isCorrect: false },
      { id: "opt_fix_by04_b", questionId: "q_fix_bio_cyc_04", displayOrder: 2, optionKey: "B", text: "They remain metabolically active but suspend division", isCorrect: true },
      { id: "opt_fix_by04_c", questionId: "q_fix_bio_cyc_04", displayOrder: 3, optionKey: "C", text: "They continuously replicate their DNA", isCorrect: false },
      { id: "opt_fix_by04_d", questionId: "q_fix_bio_cyc_04", displayOrder: 4, optionKey: "D", text: "They undergo immediate apoptosis", isCorrect: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
