"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowUpRight, Lightbulb, History } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { SectionHeader } from "@/components/shared/section-header";
import { EmptyState } from "@/components/shared/empty-state";
import type { AnalyticsInsight, RecentChangeItem } from "@/domain/analytics";
import { cn } from "@/lib/utils/cn";

/**
 * Deterministic insights ("Based on your recorded activity…") and the
 * recent-changes feed. Both render statements generated by the analytics
 * domain from stored records — nothing is invented here.
 */

export function InsightsSection({ insights }: { insights: AnalyticsInsight[] }) {
  return (
    <section aria-labelledby="insights-heading">
      <SectionHeader
        title="Based on Your Recorded Activity"
        description="Factual takeaways computed from your data"
      />
      <span id="insights-heading" className="sr-only">
        Insights
      </span>
      {insights.length === 0 ? (
        <EmptyState
          icon={<Lightbulb className="h-6 w-6" aria-hidden="true" />}
          title="Not enough data yet"
          description="Insights appear here as soon as your preparation activity is recorded."
        />
      ) : (
        <ul className="space-y-2.5">
          {insights.map((insight) => (
            <li key={insight.id}>
              <Card
                className={cn(
                  "flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between",
                  insight.kind === "attention" ? "border-warning/30" : undefined
                )}
              >
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={insight.kind === "attention" ? "warning" : "secondary"}
                      className="shrink-0"
                    >
                      {insight.title}
                    </Badge>
                  </div>
                  <p className="mt-1.5 text-sm text-foreground">{insight.detail}</p>
                </div>
                {insight.href && (
                  <Link
                    href={insight.href}
                    className="inline-flex shrink-0 items-center gap-1 self-start rounded text-sm font-medium text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:self-center"
                  >
                    {insight.hrefLabel ?? "View"}
                    <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
                  </Link>
                )}
              </Card>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

export function RecentChangesSection({ items }: { items: RecentChangeItem[] }) {
  return (
    <section aria-labelledby="recent-changes-heading">
      <SectionHeader
        title="Recent Changes"
        description="Milestones recorded in the selected period"
      />
      <span id="recent-changes-heading" className="sr-only">
        Recent changes
      </span>
      {items.length === 0 ? (
        <EmptyState
          icon={<History className="h-6 w-6" aria-hidden="true" />}
          title="Nothing recorded in this period"
          description="Topics learned, practiced, revised and mocks completed will appear here."
        />
      ) : (
        <Card className="divide-y divide-border-subtle">
          {items.map((item) => (
            <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3">
              <div className="min-w-0">
                {item.href ? (
                  <Link
                    href={item.href}
                    className="inline-flex items-center rounded text-sm font-medium text-foreground transition-colors hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  >
                    {item.label}
                  </Link>
                ) : (
                  <span className="text-sm font-medium text-foreground">{item.label}</span>
                )}
                {item.detail && (
                  <p className="mt-0.5 truncate text-xs text-muted-foreground">{item.detail}</p>
                )}
              </div>
              <span className="shrink-0 text-xs tabular-nums text-foreground-subtle">
                {formatChangeDate(item.at)}
              </span>
            </div>
          ))}
        </Card>
      )}
    </section>
  );
}

function formatChangeDate(d: Date): string {
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short" });
}
